### ISSUE TITLE
这个如果是使用自己的机子怎么部署

### ISSUE THREAD

**Issue by afycn** [april-projects/april-google-proxy#2]

**Comment by mobaijun** [comment]
在你的项目根目录下运行以下命令，以安装所有依赖项：

```bash
npm install
```

这将会安装 next、react、react-dom、eslint、eslint-config-next 和 http-proxy-middleware 等依赖项。

接着，你可以使用以下命令运行开发服务器：

```bash
npm run dev
```

这将启动 Next.js 的开发服务器，使你能够在本地进行开发。在开发过程中，你可以通过访问 http://localhost:3000 来查看你的应用。

当你准备好部署到生产环境时，可以使用以下命令构建你的项目：

```bash
npm run build
```

然后，启动生产服务器：

```bash
npm start
```

请确保你的服务器环境中安装了 Node.js，并且可以运行上述命令。部署前，你可能需要根据实际情况配置服务器，如端口、反向代理等。

**Comment by mobaijun** [comment]
如果你的机器非大陆则推荐，否则不推荐，因为服务是通过vercel来实现代理的
